import type { Metadata } from "next";
import "../globals.css";
import React from "react";
// import BottomBar from "@/components/BottomBar";
import LeftSidebar from "@/components/LeftSidebar";
import RightSidebar from "@/components/RightSidebar";
import TopBar from "@/components/TopBar";

export const metadata: Metadata = {
  title: "Home | Straytostay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <TopBar />

      <main className="flex h-[91vh] w-screen flex-row overflow-hidden">
        <LeftSidebar />
        <section className="flex size-full flex-col overflow-y-auto">
          {children}
        </section>

        <RightSidebar />
      </main>

      {/* <BottomBar /> */}
    </>
  );
}
